version: '3.7'

services:
    micro-public:
        image: us.gcr.io/${TARGET_PROJECT_ID}/${SERVICE_NAME}/${TARGET_ALIAS}:${TARGET_IMAGE_TAG}
        build:
            context: .
            args:
                - TARGET_ALIAS
                - TARGET_IMAGE_TAG
                - SERVICE_NAME
                - TARGET_PROJECT_ID
        container_name: micro_public_${TARGET_ALIAS}
        restart: unless-stopped
        env_file:
            - ".env.local.yml"
        ports:
            - "4400:8080"
